import "../globals.css"
import Footer from "../components/Footer";
import Header from "../components/Header";
import { ReduxProvider } from "../components/ReduxPovider";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
        <div className="bg-black">

        <Header/>

        </div>
        {children}
        <Footer/>
        </ReduxProvider>
      </body>
    </html>
  )
}
