import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/globals.css";
<<<<<<< HEAD
import { ReduxProvider } from "./components/ReduxPovider";
=======
>>>>>>> 547e5482b751d16a272f7a53f853496ae5f287a2
  

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ReduxProvider>
        {children}
<<<<<<< HEAD
       
        </ReduxProvider>
=======
        {/* <Footer/> */}
>>>>>>> 547e5482b751d16a272f7a53f853496ae5f287a2
      </body>
    </html>
  );
}
